#!/usr/local/bin/lua
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by serhii.dudar.
--- DateTime: 09.05.2024 23:31
---
print("test data")

io.output():write("Hello world, from ", _VERSION, "!\n")
-- or short
io.write("Hello world, from ", _VERSION, "!\n")

--comments

--[[
my first program in Lua
bla bla bla
--]]

--fruit = apples + oranges   --get the total fruit