// Tests using `go.uber.org/mock/gomock`. Normally mocks are generated by
// `mockgen`; here we write them by hand to keep the example self-contained
// and identical to what `mockgen -source=services.go` would produce.
package services

import (
	"errors"
	"testing"

	"go.uber.org/mock/gomock"
)

// -----------------------------------------------------------------------------
// Hand-written mocks (equivalent to `mockgen` output).
// -----------------------------------------------------------------------------

type MockPriceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPriceProviderRecorder
}

type MockPriceProviderRecorder struct{ mock *MockPriceProvider }

func NewMockPriceProvider(ctrl *gomock.Controller) *MockPriceProvider {
	m := &MockPriceProvider{ctrl: ctrl}
	m.recorder = &MockPriceProviderRecorder{m}
	return m
}

func (m *MockPriceProvider) EXPECT() *MockPriceProviderRecorder { return m.recorder }

func (m *MockPriceProvider) PriceOf(symbol string) (int, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PriceOf", symbol)
	return ret[0].(int), ret[1].(bool)
}

func (r *MockPriceProviderRecorder) PriceOf(symbol any) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "PriceOf", symbol)
}

type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierRecorder
}

type MockNotifierRecorder struct{ mock *MockNotifier }

func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	m := &MockNotifier{ctrl: ctrl}
	m.recorder = &MockNotifierRecorder{m}
	return m
}

func (m *MockNotifier) EXPECT() *MockNotifierRecorder { return m.recorder }

func (m *MockNotifier) Notify(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", message)
	if ret[0] == nil {
		return nil
	}
	return ret[0].(error)
}

func (r *MockNotifierRecorder) Notify(message any) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "Notify", message)
}

// -----------------------------------------------------------------------------
// Tests
// -----------------------------------------------------------------------------

func TestPortfolio_GoMock_Sum(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	prices := NewMockPriceProvider(ctrl)
	prices.EXPECT().PriceOf("AAPL").Return(180, true).Times(1)
	prices.EXPECT().PriceOf("MSFT").Return(420, true).Times(1)

	notes := NewMockNotifier(ctrl)
	notes.EXPECT().Notify("total=600").Return(nil).Times(1)

	p := &Portfolio{Provider: prices, Notifier: notes}
	got, err := p.Total([]string{"AAPL", "MSFT"})
	if err != nil || got != 600 {
		t.Fatalf("got %d, %v; want 600, nil", got, err)
	}
}

func TestPortfolio_GoMock_Error(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	prices := NewMockPriceProvider(ctrl)
	prices.EXPECT().PriceOf(gomock.Any()).Return(10, true).AnyTimes()

	notes := NewMockNotifier(ctrl)
	notes.EXPECT().Notify(gomock.Any()).Return(errors.New("boom"))

	p := &Portfolio{Provider: prices, Notifier: notes}
	if _, err := p.Total([]string{"X"}); err == nil {
		t.Fatal("expected error")
	}
}
